### ISSUE TITLE
Inquiry about Development Details for Hugoecom's Texture Pack

### ISSUE THREAD

**Issue by phiuuu** [Hugoecom/MC#1]
Hello Hugoecom! I'm highly interested in the development of your texture pack and would love to gather more information about it. I have a few specific questions regarding the direction you'll be taking this year. I would appreciate it if you could address them.

1. Which game version is the texture pack being developed for?
2. Will it feature integrated 3D models for blocks and in-game elements?
3. Are there any plans for custom user interfaces (GUIs) to create a unique visual experience?
4. Can we expect custom-designed weapons within the texture pack?
5. I would be grateful for any insights you can provide regarding these features. I'm excited about the texture pack's development and look forward to seeing its progress!

Best regards,
Phiuu

**Comment by Hugoecom** [comment]
**Which game version is the texture pack being developed for?**
_The texture pack is being developed specifically for Minecraft version 1.19.4._

**Will it feature integrated 3D models for blocks and in-game elements?**
_Yes, we will be incorporating a variety of meticulously crafted and sourced 3D models, including furniture, mobs, hats, misc items, and more._

**Are there any plans for custom user interfaces (GUIs) to create a unique visual experience?**
_Absolutely! We are actively working on creating several custom GUIs, ensuring a distinct and immersive visual experience for our users._

**Can we expect custom-designed weapons within the texture pack?**
_Yes, we have designed complete sets of custom weapons and armor. Additionally, we will be introducing custom food items to enhance the gameplay experience._

**Comment by phiuuu** [comment]
Thank you sincerely for your hard work and dedication in creating this texture pack. I'm excited to see the progress and have the opportunity to collaborate with you and enjoy it in my game.

I appreciate your kindness and detailed responses to my questions. I wish you all the best in the ongoing development of the texture pack.

Best regards,
phiuu
